[ENGX-5]: Add Sentry
lux-group/router pull request #30
Opened 2021-06-25 05:12 UTC by moixons

2021-06-28 00:03 UTC, keithbro requested changes
Taking a step back I think the ACs of the task should be:

* Using the existing approach of `server.use(errorHandler)` should enable Sentry if the env var is set
* Sentry should receive only 5xx errors

2021-06-28 00:45 UTC, moixons commented on lib/middleware/request-validator.js
> +      errorManager({ logger, warnOnRequestValidationError, typeError: 'url path parameters', errors })
Probably, I should have created another PR for this change. because it is not related to adding Sentry. It is a refactor of the function

2021-06-28 00:47 UTC, moixons commented
> Taking a step back I think the ACs of the task should be:
> 
> * Using the existing approach of `server.use(errorHandler)` should enable Sentry if the env var is set
> * Sentry should receive only 5xx errors

Ah, the task didn't have any AC, so I assumed that we want to send all the errors to Sentry. I'll change according to this.

2021-06-28 00:58 UTC, moixons commented on lib/router.js
> +  if (sentryDSN) app.use(Sentry.Handlers.errorHandler())
So, each service is responsible for adding Sentry.errorHandler, and the only thing we need to do here is to send the 4xx errors to Sentry?

2021-06-28 01:00 UTC, moixons commented on package.json
> +    "@sentry/node": "^6.7.2",
Good point. I'll change it to be a peerDependency

2021-06-29 20:21 UTC, nguyenchr commented
> Taking a step back I think the ACs of the task should be:
> 
> * Using the existing approach of `server.use(errorHandler)` should enable Sentry if the env var is set
> * Sentry should receive only 5xx errors

Is it possible to do with an env var being set?
I'm not a huge fan of libs requiring env vars being set in the consuming services, it makes it hard to figure out where the env var is being used as a developer of the service IMO

2021-07-09 01:58 UTC, nguyenchr commented on index.d.ts
> +    appEnv: 'development' | 'spec' | 'test' | 'production';
I think this is optional?

2021-07-09 02:00 UTC, nguyenchr commented on lib/sentry.js
> +    logger.debug('Setting up Sentry errorHandler')
the type interface for Logger currently only expect info warn and error https://github.com/lux-group/router/blob/e72b1c43206326b68dad502c8f992ef956cdcaba/index.d.ts#L16

2021-07-09 02:03 UTC, nguyenchr approved these changes

2021-07-12 02:36 UTC, nguyenchr commented on package.json
> -  "optionalDependencies": {
should we update the readme then to give instruction that you need to have sentry/openapi-typescript installed if you want to use those features?

2021-07-12 02:36 UTC, nguyenchr approved these changes

2021-07-14 01:17 UTC, keithbro commented on package.json
> -  "optionalDependencies": {
done thanks!

2021-07-14 20:35 UTC, nguyenchr approved these changes

2021-07-14 22:00 UTC, merged