fix(sentry): fix the type of init sentry
lux-group/router pull request #38
Opened 2021-11-23 21:05 UTC by reb2020

2021-11-23 22:06 UTC, nguyenchr commented on index.d.ts
> -    sentryDSN?: string;
I don't think this is correct, the sentryDSN opt is still needed for the router router type, this is used when initialising sentry automatically 

https://github.com/lux-group/router/blob/master/lib/router.js#L99-L104

2021-11-23 22:07 UTC, nguyenchr commented on package.json
> +  "version": "1.0.2",
removing a type would be a breaking change

2021-11-23 22:07 UTC, nguyenchr commented on package.json
> +  "version": "1.0.2",
although I don't think that type needs to be removed, just added in addition to initialize

2021-11-23 22:39 UTC, keithbro reviewed
What's the problem you're running in to? Could you provide some more details please?

2021-11-24 06:08 UTC, reb2020 commented on package.json
> +  "version": "1.0.2",
Yes, you are right
I have removed that occasionally

2021-11-25 19:56 UTC, nguyenchr approved these changes
I think this looks good

2021-11-25 21:02 UTC, keithbro requested changes

2021-11-25 21:02 UTC, keithbro commented on README.md
> +initializeSentry({
I don't think we should add this here. You'd never initialise it before the creating the router like this because the router initializes Sentry itself and has to hook it up in certain way. Maybe this could be in a different section of the README that explains how to make it work with background jobs?

2021-11-26 06:17 UTC, reb2020 commented on README.md
> +initializeSentry({
Yes that my main reason to add this case into readme because we have a lot of places where we initialised it in different places but we already have that in route

2021-11-26 06:35 UTC, keithbro approved these changes

2021-11-26 07:06 UTC, merged